modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tridenchantability"
version = "${version}"
displayName = "Tridenchantability"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""

[[mixins]]
config = "tridenchantability.mixins.json"
